sudo: false
language: java
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
install: gradle setupCIWorkspace -S
script: gradle build
notifications:
  email: false
env:
  global:
    TERM=dumb

